/**
 * 💡 整合完成後，其他網頁只需要引入此單一檔案即可：
 * <script src="ime-button.js"></script>
 */

// ==========================================
// 1. 輔助工具：動態載入外部 JavaScript 檔案
// ==========================================
function loadScript(src) {
    return new Promise((resolve, reject) => {
        if (document.querySelector(`script[src="${src}"]`)) {
            resolve();
            return;
        }
        const script = document.createElement('script');
        script.src = src;
        script.onload = () => resolve();
        script.onerror = () => reject(new Error(`無法載入腳本: ${src}`));
        document.head.appendChild(script);
    });
}

// ==========================================
// 2. 輔助工具：內嵌樣式與字型樣式注入
// ==========================================
function injectImeButtonStyles() {
    const styleId = 'ime-toggle-button-styles';
    if (document.getElementById(styleId)) {
        return;
    }
    
    const css = `
		.ime-toggle-button, 
		#ime-external-toolbar-container,
		.webime-window,
		.ime-panel,
		#ime-main-container {
		    font-family: twhei-s, TWHEI, "台灣黑體", tauhu-oo, PingFangTC-Regular, "Microsoft JhengHei", sans-serif !important;
		}

		.ime-toggle-button {
		    display: inline-flex; align-items: center; justify-content: center;
		    cursor: pointer; box-shadow: 0 2px 5px rgba(0,0,0,0.2);
		    color: #5f6368; outline: none;
		}
		.ime-toggle-button.ime-active { background-color: #e8f0fe; color: #1a73e8; }
		.ime-toggle-button.ime-active:hover { background-color: #d2e3fc; color: #1C73C8; }
    `;
    const styleElement = document.createElement('style');
    styleElement.id = styleId;
    styleElement.innerHTML = css;
    document.head.appendChild(styleElement);
}

// ==========================================
// 3. 主環境非同步初始化流程
// ==========================================
async function initImeEnvironment() {
    try {
        // 抓取目前這支 ime-button.js 所在的絕對路徑目錄
        // 如果抓不到，預設 fallback 到 GitHub Pages 網址
        let baseUrl = 'https://gnisew.github.io/tools/ime/';
        const currentScript = document.currentScript || document.querySelector('script[src*="ime-button.js"]');
        if (currentScript && currentScript.src) {
            baseUrl = currentScript.src.substring(0, currentScript.src.lastIndexOf('/') + 1);
        }

        // [步驟 A-1] 自動引入 ime.css
        if (!document.querySelector('link[href*="ime.css"]')) {
            const link = document.createElement('link');
            link.rel = 'stylesheet';
            link.href = baseUrl + 'ime.css'; 
            document.head.appendChild(link);
        }

        // [步驟 A-2] 自動引入「台灣黑體」字型檔
        if (!document.querySelector('link[href*="twhei.css"]')) {
            const fontLink = document.createElement('link');
            fontLink.rel = 'stylesheet';
            fontLink.href = 'https://oikasu1.github.io/kasuexam/kasu/fonts/twhei.css';
            document.head.appendChild(fontLink);
        }

        // [步驟 B] 自動引入 Material Symbols 圖示庫 (已修正為支援 outlined 的版本)
        if (!document.querySelector('link[href*="Material+Symbols"]')) {
            const iconLink = document.createElement('link');
            iconLink.rel = 'stylesheet';
            iconLink.href = 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined';
            document.head.appendChild(iconLink);
        }

        // [步驟 C] 依序非同步載入相依的 JS 檔案
        await loadScript(baseUrl + 'ime-dict.js');
        await loadScript(baseUrl + 'ime.js');

        // [步驟 D] 自動生成按鈕與拖曳邏輯
        let autoGeneratedBtn = document.querySelector('.ime-toggle-button');
        if (!autoGeneratedBtn) {
            autoGeneratedBtn = document.createElement('button');
            autoGeneratedBtn.className = 'ime-toggle-button icon-btn hover:bg-blue-50 hover:text-blue-600';
            autoGeneratedBtn.title = '開啟/關閉輸入法 (可拖曳移動)';
            // 縮小 icon 尺寸
            autoGeneratedBtn.innerHTML = '<span class="material-symbols-outlined" style="font-size: 20px;">keyboard</span>';
            
            // 將尺寸從 50px 縮小至 40px，使其更不突兀
            Object.assign(autoGeneratedBtn.style, {
                position: 'fixed', bottom: '20px', right: '20px', zIndex: '9999',
                backgroundColor: '#ffffff', border: '1px solid #e0e0e0',
                borderRadius: '50%', width: '40px', height: '40px',
                cursor: 'pointer', touchAction: 'none', // 避免手機端拖曳時畫面跟著捲動
                transition: 'left 0.3s, right 0.3s, bottom 0.3s, background-color 0.2s, color 0.2s'
            });
            document.body.appendChild(autoGeneratedBtn);

            // --- 拖曳與智慧吸附邏輯 ---
            let dragStartX, dragStartY;
            
            // 自訂屬性，用來區分「點擊」和「拖曳」
            autoGeneratedBtn.isDraggingAction = false; 

            const handleDragStart = (e) => {
                autoGeneratedBtn.isDraggingAction = false;
                const clientX = e.touches ? e.touches[0].clientX : e.clientX;
                const clientY = e.touches ? e.touches[0].clientY : e.clientY;
                dragStartX = clientX;
                dragStartY = clientY;

                document.addEventListener('mousemove', handleDragMove);
                document.addEventListener('touchmove', handleDragMove, {passive: false});
                document.addEventListener('mouseup', handleDragEnd);
                document.addEventListener('touchend', handleDragEnd);
                
                // 拖曳時取消位置的動畫過渡，讓按鈕乖乖跟著滑鼠/手指
                autoGeneratedBtn.style.transition = 'background-color 0.2s, color 0.2s';
            };

            const handleDragMove = (e) => {
                const clientX = e.touches ? e.touches[0].clientX : e.clientX;
                const clientY = e.touches ? e.touches[0].clientY : e.clientY;
                
                const dx = clientX - dragStartX;
                const dy = clientY - dragStartY;
                
                // 若移動超過 5px 則判定為拖曳，非點擊
                if (Math.abs(dx) > 5 || Math.abs(dy) > 5) {
                    autoGeneratedBtn.isDraggingAction = true;
                    e.preventDefault();
                    
                    autoGeneratedBtn.style.left = (clientX - 20) + 'px';
                    autoGeneratedBtn.style.top = (clientY - 20) + 'px';
                    autoGeneratedBtn.style.right = 'auto';
                    autoGeneratedBtn.style.bottom = 'auto';
                }
            };

            const handleDragEnd = (e) => {
                document.removeEventListener('mousemove', handleDragMove);
                document.removeEventListener('touchmove', handleDragMove);
                document.removeEventListener('mouseup', handleDragEnd);
                document.removeEventListener('touchend', handleDragEnd);
                
                // 恢復過渡動畫，為了接下來的「吸附效果」
                autoGeneratedBtn.style.transition = 'left 0.3s, right 0.3s, bottom 0.3s, top 0.3s, background-color 0.2s, color 0.2s';
                
                if (autoGeneratedBtn.isDraggingAction) {
                    let clientX = e.changedTouches ? e.changedTouches[0].clientX : e.clientX;
                    const screenHalf = window.innerWidth / 2;
                    
                    autoGeneratedBtn.style.top = 'auto';
                    autoGeneratedBtn.style.bottom = '20px'; // 固定在下方
                    
                    // 智慧吸附：判斷在左半邊還是右半邊
                    if (clientX < screenHalf) {
                        autoGeneratedBtn.style.left = '20px';
                        autoGeneratedBtn.style.right = 'auto';
                    } else {
                        autoGeneratedBtn.style.right = '20px';
                        autoGeneratedBtn.style.left = 'auto';
                    }
                    
                    // 稍微延遲解除拖曳狀態，防止觸發 click 事件
                    setTimeout(() => { autoGeneratedBtn.isDraggingAction = false; }, 50);
                }
            };

            autoGeneratedBtn.addEventListener('mousedown', handleDragStart);
            autoGeneratedBtn.addEventListener('touchstart', handleDragStart, {passive: true});
        }

        // [步驟 E] 注入按鈕與字型的 CSS 樣式
        injectImeButtonStyles();

        // ==========================================
        // 4. 核心邏輯：URL 參數處理與按鈕事件監聽
        // ==========================================
        const toggleButtons = document.querySelectorAll('.ime-toggle-button');
        const hasToggleButtons = toggleButtons.length > 0;
        const params = new URLSearchParams(window.location.search);

        function syncAllToggleButtonsUI() {
            const isActive = typeof WebIME !== 'undefined' && WebIME.isInitialized;
            const externalToolbar = document.getElementById('ime-external-toolbar-container');

            toggleButtons.forEach(button => {
                if (isActive) {
                    button.title = '關閉輸入法 (可拖曳移動)';
                    button.classList.add('ime-active');
                } else {
                    button.title = '開啟輸入法 (可拖曳移動)';
                    button.classList.remove('ime-active');
                }
            });

            if (!isActive && externalToolbar) {
                externalToolbar.innerHTML = '';
            }
        }

        // --- 【URL 參數處理邏輯】 ---
        if (params.has('ime')) {
            const imeParam = params.get('ime');
            const parts = imeParam.split('-');
            const imeState = parts[0]; 

            if (imeState === '0') {
                const newUrl = new URL(window.location.href);
                newUrl.searchParams.delete('ime');
                window.history.replaceState({}, document.title, newUrl.href);
                return;
            }

            const configFromUrl = {};
            const features = {};

            if (parts.length === 3) {
                configFromUrl.defaultMode = parts[1];
                const settingsCode = parts[2];

                if (settingsCode.length >= 1) features.singleCharMode = (settingsCode[0] === '1');
                if (settingsCode.length >= 2) features.prediction = (settingsCode[1] === '1');
                if (settingsCode.length >= 3) features.numericTone = (settingsCode[2] === '1');
                if (settingsCode.length >= 4) features.longPhrase = (settingsCode[3] === '1');
                if (settingsCode.length >= 5) features.fullWidthPunctuation = (settingsCode[4] === '1');
                
                if (settingsCode.length >= 6) {
                    features.outputEnabled = (settingsCode[5] === '1');
                }
                if (settingsCode.length >= 7) {
                    switch(settingsCode[6]) { 
                        case '1': features.outputMode = 'pinyin_mode'; break;
                        case '2': features.outputMode = 'pinyin'; break;
                        case '3': features.outputMode = 'word_pinyin'; break;
                        case '4': features.outputMode = 'word_pinyin2'; break;
                    }
                }
            }
            
            configFromUrl.features = features;

            if (typeof WebIME !== 'undefined') {
                WebIME.imeInit(configFromUrl);

                if (imeState === '1') {
                    WebIME.imeSetIsEnabled(true);
                } else if (imeState === '2') {
                    WebIME.imeSetIsEnabled(false);
                }
            }

            const newUrl = new URL(window.location.href);
            newUrl.searchParams.delete('ime');
            window.history.replaceState({}, document.title, newUrl.href);

        } else {
            if (!hasToggleButtons && typeof WebIME !== 'undefined') {
                WebIME.imeInit();
            }
        }

        syncAllToggleButtonsUI();

        toggleButtons.forEach(button => {
            button.addEventListener('click', (e) => {
                // 如果剛剛是在拖曳按鈕，就攔截這次點擊，不執行開關輸入法
                if (button.isDraggingAction) {
                    e.preventDefault();
                    e.stopPropagation();
                    return;
                }

                if (typeof WebIME !== 'undefined') {
                    if (WebIME.isInitialized) {
                        WebIME.imeDestroy();
                    } else {
                        WebIME.imeInit();
                    }
                    syncAllToggleButtonsUI();
                }
            });
        });

    } catch (error) {
        console.error("輸入法環境動態載入或初始化失敗：", error);
    }
}

// ==========================================
// 5. 確保在 DOM Ready 後才啟動初始化
// ==========================================
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initImeEnvironment);
} else {
    initImeEnvironment();
}